---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "gwa.fullname" . }}
  labels:
    {{- include "gwa.runnerLabels" . | nindent 4 }}
spec:
  {{- if .Values.service.headless }}
  clusterIP: None
  {{- else }}
  type: {{ .Values.service.type }}
  {{- end }}
  selector:
    {{- include "gwa.runnerSelectorLabels" . | nindent 4 }}
  ports:
    {{- range .Values.service.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
    {{- end }}
